#include "txt.h"

TXT::TXT() :
    ExportMethod("Text")
{
}

void TXT::saveAs(const QVector<QPair<QString, QString>>& password)
{
    ofstream exportFile("Passwords.txt");
    if(exportFile.is_open())
    {
        exportFile << "Passwords generated by Generator a C++ random password generator.\n";
        exportFile << "Find more on github.com/joabda/Generator\n";
        for(auto& oneElement : password)
            exportFile << "Password for " << oneElement.first.toStdString() << " is : " << oneElement.second.toStdString() << ".\n";
        exportFile << "Generated on " << QDate::currentDate().toString().toStdString() << endl;
    }
    else
        fprintf(stderr, "Error opening file\n");
}

QString TXT::getName() const
{
    return name_;
}
